// <auto-generated />
using System;
using ECommerce.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508115217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECommerce.API.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ECommerce.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 5, 8, 11, 52, 15, 73, DateTimeKind.Utc).AddTicks(7923),
                            Description = "Apple M3 Pro chip, 18GB RAM, 512GB SSD",
                            ImageUrl = "https://picsum.photos/id/0/400/400",
                            IsFeatured = true,
                            Name = "MacBook Pro 14",
                            Price = 189999m,
                            Stock = 10
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 5, 8, 11, 52, 15, 73, DateTimeKind.Utc).AddTicks(7928),
                            Description = "6.7-inch display, A17 Pro chip, 256GB",
                            ImageUrl = "https://picsum.photos/id/1/400/400",
                            IsFeatured = true,
                            Name = "iPhone 15 Pro Max",
                            Price = 149999m,
                            Stock = 15
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Audio",
                            CreatedAt = new DateTime(2026, 5, 8, 11, 52, 15, 73, DateTimeKind.Utc).AddTicks(7952),
                            Description = "Industry-leading noise cancellation",
                            ImageUrl = "https://picsum.photos/id/2/400/400",
                            IsFeatured = true,
                            Name = "Sony WH-1000XM5",
                            Price = 29999m,
                            Stock = 25
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 5, 8, 11, 52, 15, 73, DateTimeKind.Utc).AddTicks(7954),
                            Description = "Quiet clicks, 8K DPI tracking",
                            ImageUrl = "https://picsum.photos/id/3/400/400",
                            IsFeatured = false,
                            Name = "Logitech MX Master 3S",
                            Price = 8999m,
                            Stock = 30
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2026, 5, 8, 11, 52, 15, 73, DateTimeKind.Utc).AddTicks(7958),
                            Description = "49-inch curved gaming monitor",
                            ImageUrl = "https://picsum.photos/id/4/400/400",
                            IsFeatured = true,
                            Name = "Samsung Odyssey G9",
                            Price = 149999m,
                            Stock = 5
                        });
                });

            modelBuilder.Entity("ECommerce.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 11, 52, 15, 73, DateTimeKind.Utc).AddTicks(7578),
                            Email = "admin@shopez.com",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$n3kplwMPRH0eb2QTIOmBSOgZ7p/JsfMR4k/mg7FZHdJgtKpw.jUju",
                            Role = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 5, 8, 11, 52, 15, 73, DateTimeKind.Utc).AddTicks(7580),
                            Email = "john@example.com",
                            Name = "John Customer",
                            PasswordHash = "$2a$11$e360DcJRo8Ek2dKHpB19lO00xVQqW9ji.Ef.OVGK0kWhEMQwZvTLS",
                            Role = "Customer"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 5, 8, 11, 52, 15, 73, DateTimeKind.Utc).AddTicks(7582),
                            Email = "jane@example.com",
                            Name = "Jane Smith",
                            PasswordHash = "$2a$11$e360DcJRo8Ek2dKHpB19lO00xVQqW9ji.Ef.OVGK0kWhEMQwZvTLS",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("ECommerce.API.Models.Order", b =>
                {
                    b.HasOne("ECommerce.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.API.Models.OrderItem", b =>
                {
                    b.HasOne("ECommerce.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.API.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ECommerce.API.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ECommerce.API.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
